#ifndef _DEFINES_H_
#define _DEFINES_H_
#define SETBIT(WORD,BITPOS) (WORD=WORD|(1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD=WORD&~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD=WORD^(1<<BITPOS))

//#define WRITEBIT(WORD,BITPOS,BITVAL) (BITVAL? SETBIT(WORD,BITPOS):(CLRBIT(WORD,BITPOS))
 #define WRITEBIT(WORD,BITPOS,BITVAL) (WORD=((WORD&~(1<<BIPTPOS))|(BITVAL<<BITPOS)))
 #define WRITENIBBEL(WORD,STARTBITPOS,NIBBELVAL) (WORD=((WORD&~(15<<STARTBITPOS))|(NIBBELVAL<<STARTBITPOS)))
 #define WRITEBYTE(WORD,STARTBITPOS,BYTEVAL) (WORD=((WORD&~(255<<STARTBITPOS))|(BYTEVAL<<STARTBITPOS)))   
 #define WRITEHWORD(WORD,STARTBITPOS,HWORDVAL) (WORD=((WORD&~(0xffff<<STARTBITPOS))|(HWORDVAL<<STARTBITPOS)))
 
 //READ THE BIT
 #define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
 #define READNIBBEL(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
 #define READBYTE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&255)
 #endif
